### ISSUE TITLE
Newest version of "Theme_Maker" released

### ISSUE THREAD

**Issue by PySimpleGUI** [definite-d/PSG-LookyFeely#1]
I can't help but notice the description of this project matching somewhat the Theme Maker program that was used to make the last large addition of "look and feel" themes for PySimpleGUI.

Take a look at this folder:
https://github.com/PySimpleGUI/PySimpleGUI/tree/master/ThemeMaker

You'll find a file with a LOT of color themes that were downloaded.  There is also a Theme_Maker.py file.  This program presents the user with 4 different "candidate themes" per palette.  A palette is a single group of 4 or more colors that were downloaded.  The candidate themes are 2 light colored and 2 dark colored.

The program enables the user to visually choose several options per candidate theme.  Here's a screenshot showing 5 palettes, each with 4 candidate themes.

![image](https://user-images.githubusercontent.com/46163555/69907872-c4c80680-13ab-11ea-8614-6607d6aba945.png)

As explained in the program's comments, the user can choose several options per candidate theme.  Those that are checked with the checkbox are used to create a look and feel dictionary entry that is output to a window as well as an output file.

I'm working on the readme to finish it out.

I'm forever looking for good color themes for users.  Gray windows suck 😊

I'm curious what features you had in mind for your project.

**Comment by definite-d** [comment]
Whoa! You're observant! I wanted this to be surprise for you and the PySimpleGUI community, but I guess you've caught me. I'm having a minor issue with GitHub as a whole; I'm trying to upload files to this repo, but after dragging in files **and** selecting files, nothing shows up. At best, the file gets opened or downloaded by my browser. Sure, you may not know how to solve that, but I thought it would be good to let you know. Here's some screenshots of the project anyway. Not uploaded yet.
(I'm not sure the screenshots may show up due to the same issue).

**Comment by definite-d** [comment]
Yep. I was right. They didn't show up.

**Comment by definite-d** [comment]
My project is pretty basic (compared to Theme Maker).

Some text inputs for color settings, padding values and a theme name and color picker buttons for each, random color generation where not supplied, code generation for the color theme (to be pasted into the user's code) and a preview window. It also selects its own look and feel upon startup from a random choice of all default themes.
I'm totally with you on having more color themes. For me, 100+ ain't enough ;).

Also, I get a 404 from clicking the link in your comment above. And I've found another issue; I can't edit comments.

**Comment by PySimpleGUI** [comment]
OOppps on the 404 error.  Last night I renamed the folder from Theme Creator to Theme Maker since that's what the .py file has always been.  I edited the comment.

**Comment by definite-d** [comment]
LookyFeely will probably be up on this repo by Saturday, since I've found that my GitHub issues only happen on my PC. Meanwhile, I've been working on a few optimizations:
- Sorry, I used exec(). But it was for a worthy cause!
- Fixed multiple issues in my own code. For example, I recently found out that the progress bar color parameter is a tuple. Silly me.

All in all, I'm aiming for "perfect" code, where this will be the only GitHub issue.

**Comment by definite-d** [comment]
Yup! It's up!
Turns out opening GitHub in a private browsing window seemed to wipe away the issue of commiting to repos.
Now, the PSG-LookyFeely script is live and ready for action.

*There's one little thing I have to ask though...* (about GitHub repo maintenance).
I can't seem to create folders on my repo, and I find it a bit embarrassing. There are folders nested in folders of folders in _your_ repository for PySimpleGUI, so any pointers on how to do that? Yes, I'm a bit of a newbie to maintaining repositories.
